### ISSUE TITLE
Does not work in Unity 2020.3

### ISSUE THREAD

**Issue by farazk86** [EntroPi-Games/Unity-Cloud-Shadows#3]
Thank you for providing this asset :)

I want to add it to my game but unfortunately its not working. 

I've followed the instructions in the pdf, which are simple enough to add your ``Cloud Shadows`` component to the directional light and ensure that the light is rendered in real time.

But the clouds dont appear in my scene. It just darkens my scene similar to how I would set the coverage to max in your demo.

Any idea why it may not be working?

Thanks

**Comment by EntroPiGames** [comment]
Are you using the built-in renderer or one of the new render pipelines (URP, HDRP)?

**Comment by farazk86** [comment]
> Are you using the built-in renderer or one of the new render pipelines (URP, HDRP)?

built in renderer

**Comment by farazk86** [comment]
Just to add some screenshots to help explain the issue.

This is what it looks like without the component

![Unity_qoNessuMMn](https://user-images.githubusercontent.com/33456896/135458402-c9889e1a-22e2-4614-b1d6-ebf7db848324.png)

This is what it looks like after adding the component

![Unity_xJXu9D1Kmz](https://user-images.githubusercontent.com/33456896/135458452-47269302-9b96-491b-8788-e478fb329198.png)

And here is the directional light gameobject with the Cloud Shadows attached

![image_2021-09-30_135251](https://user-images.githubusercontent.com/33456896/135458539-5c7b1cd6-84d4-4574-a4a1-f5391094c5f3.png)

Also, as suggested in documentation I am using ``Forward`` rendering path

Any idea what may be the problem or how I can fix this?

**Comment by EntroPiGames** [comment]
Are you using any custom shaders in your project?

**Comment by farazk86** [comment]
> Are you using any custom shaders in your project?

just the standard pipeline and no custom shaders in scene

**Comment by Radivarig** [comment]
Try replacing `color.a = ` with `color.rgba = ` in the shader like [here](https://github.com/EntroPi-Games/Unity-Cloud-Shadows/pull/5/files#diff-e6856fe80e75c8b7aa0eaabf5c2c1f7c84f984d0c66bca4fe17f8b8e79ab6e53R80).

**Comment by farazk86** [comment]
So after all this time I came back to my previous project and tried the clouds again and I figures=d out why it didnt work.

My ground material was using the Mobile/Diffuse shader instead of the Standard shader. Changing it to standard made the clouds show up...

so yeah.. my bad all along, but this was never mentioned in the documentation..
